import MainLayout from "@components/layouts/main-layout";
import type { NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data } = useSession();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        Strona główna{" "}
        <button onClick={() => signIn("google")}>login with google</button>
      </MainLayout>
    </>
  );
};

export default Home;
